### ISSUE TITLE
Algorithm provides only one (and frequently wrong) candidate for the disambiguations

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#140]
It is strange, that in the case of artists2.csv ( https://drive.google.com/file/d/0B7AckGrBKzUtaGp1OTdKSGxTM0k/view?usp=sharing ), the algorithm only provides one candidate, and frequently not the most obvious one (like Haifa film instead of the city, Israel national team instead of the Israel state itself and so on).

**Comment by brodecva** [comment]
Please look at this, if you get some free time. I do not expect it to be fixed in the second iteration.

**Comment by tomas-knap** [comment]
We got into that again on Friday, writting email to Ziqi.

**Comment by tomas-knap** [comment]
From Ziqi: 

Hi Tomas


I noticed that as well, for dbpedia. 


It is not a desired behaviour but it is so because of the way we query for candidates on dbpedia. We use exact string match first, and if no match, we use regex. So in most cases, there will be one exact match.


Before with freebase, the search api provided by freebase is like a free text search engine, hence we got many candidates. But because dbpedia is a sparql database and because of the limitation it has w.r.t. text matching, it does not work like freebase.


Ideally, we should firstly build an inverted index of labels of all URIs in dbpedia, and use that instead of doing string matching on labels using sparql.

**Comment by tomas-knap** [comment]
As proposed by Ziqi, it may make sense to build an inverted index of labels of all URIs in dbpedia, and use that instead of doing string matching on labels using sparql.

@JanVana Please write a page to wiki on that, proposing also the solution (or more alternative solutions). Do not spend more then 2-3h on that

**Comment by tomas-knap** [comment]
There is a change in the pull request #255 which causes more candidates are depicted. THere was a (probably bug?) in the code which cause that only one disambiguation was taken into account

**Comment by brodecva** [comment]
> There is a change in the pull request #255 which causes more candidates are depicted. THere was a (probably bug?) in the code which cause that only one disambiguation was taken into account

> Nevertheless, as a result, the algorithm is even a bit more slower.

Unfortunately, the algorithm does not return multiple candidates in its current state, so I have to re-open this. We will discuss if we fix it, and if, than in what time frame.

**Comment by JanVana** [comment]
After some further testing, I have to report, that the algorithm does return multiple results. Example: Cell value "Erikson" returns quite a lot results.

The issue may be caused by the following search behavior:
1) Exact search is performed.
2) Exact result is found.
3) No fulltext search is performed, because there is already a result.

**Comment by brodecva** [comment]
> After some further testing, I have to report, that the algorithm does return multiple results. Example: Cell value "Erikson" returns quite a lot results.
>
>The issue may be caused by the following search behavior:
>
>    Exact search is performed.
>    Exact result is found.
>    No fulltext search is performed, because there is already a result.

@JanVana Thx for clearing that up. Closing again.
