### ISSUE TITLE
Support properly different encodings, delimiters in the algorithm

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#157]
![screen shot 2016-09-09 at 12 00 21](https://cloud.githubusercontent.com/assets/3014917/18383277/1089073a-7685-11e6-8821-cb2660a2fa34.png)

As the file is uploaded, it would be nice to pre-set the line endings properly, so that user does not need to set that manually. Also we may try to pre-set the delimiters automatically by examining e.g. first row. 

Pre-setting the encoding is a bit more challenging, would suggest to let the user select (UTF-8 by default), later we may improve.

**Comment by brodecva** [comment]
@tomas-knap The currently used library (Apache Commons) does not need the line separators specified. On the other hand we might need to know them when constructing the extended CSV with annotations, in order to return the user a CSV file that is more-or-less similar to the one that was put in. I will create a separate task for that.

Concerning the automatic detection of field delimiters, the used library does not provide this feature. I will create a separate issue for that, but assign a low priority to it.

The same for the character set detection. Unless we find a suitable library, the time requirements for this feature are out of scope for the time being.
