### ISSUE TITLE
Mixed line endings, not expected result

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#158]
Develop branch from 7.9.
Processing file: 
[Books-v5-lf.csv.zip](https://github.com/odalic/sti/files/463708/Books-v5-lf.csv.zip)

WHen processing such file, I got (see the last line): 
![screen shot 2016-09-09 at 11 51 09](https://cloud.githubusercontent.com/assets/3014917/18383223/d0047cc6-7684-11e6-9e9e-369853c504f6.png)

The reason for that is that CRLF is used after first two lines, but LF only is used before the last line.

Relates with #157 . But the algorithm should be able to cope with intermixed line endings or at least produce warning.  @brodecva, @istvan-satmari Please propose the correct behaviour in such cases.

**Comment by brodecva** [comment]
@tomas-knap Changing it to feature, if you don't mind. The current way of handling such irregular data seems relatively reasonable and what you ask for requires a good deal of thinking on its own on the parser side.

@tomas-knap Couple of notes and questions:
- How frequent is the case when a file intermixes line endings (this is a place where a reasonable sized test data might come handy)? To be honest I might come across such files only couple of times in my life and it was usually due to my own error when creating them from individual characters. Was the example altered or did the original data mixed the EOLs naturally?
- I would try to rely on the capabilities of the current CSV parser library, or its replacement, if there is a one, that deals with your requirement directly.

@istvan-satmari If I remember correctly, the client relies on its own parser to display the file in cells. This is a good enough solution for the quick prototype, but as more of these requests will come, we should remove this duplication of efforts and leave the parsing solely to the server. The client would use the API to retrieve the input file already parsed into a data structure (this method already exists in the API).

**Comment by brodecva** [comment]
@tomas-knap @istvan-satmari
Concerning the solution, I am for having an Auto option that would do its best to guess the author's intent (as far as the parser is able to), but also keep manual options (at least for popular systems) also available.

Consider that determining the EOL can become rather complex, if you decide to support minority and older platforms. It might also depend on the used encoding. See at https://en.wikipedia.org/wiki/Newline .

**Comment by tomas-knap** [comment]
The best would be if the parser library can deal with that automatically. 

I managed to get file with intermixed line endings by taking books.csv and adding new line on mac os. I think this is not typical, but it has to at least correctly identify CRLF vs. LF and display that correctly.

**Comment by tomas-knap** [comment]
Postponing, currently marking as won't fix, as there may be a chance to use csvcleaner for that.
