### ISSUE TITLE
Results of elections in Voralrlberg 2009

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#174]
https://grips.semantic-web.at/x/sASBB

**Comment by tomas-knap** [comment]
The file: https://www.data.gv.at/katalog/dataset/landtagswahlergebnisse/resource/cb9f662e-2a2b-4df4-bfbf-8dca29bbbb91

The task failed immediately: 

```
.15:34:15.026 [http-nio-8080-exec-2] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting OPTIONS for path tasks/LT-2009/execution 
.15:34:15.027 [http-nio-8080-exec-2] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Reply "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8YXBwbGljYXRpb24geG1sbnM9Imh0dHA6Ly93YWRsLmRldi5qYXZhLm5ldC8yMDA5LzAyIj4KICAgIDxkb2MgeG1sbnM6amVyc2V5PSJodHRwOi8vamVyc2V5LmphdmEubmV0LyIgamVyc2V5OmdlbmVyYXRlZEJ5PSJKZXJzZXk6IDIuMjMuMSAyMDE2LTA2LTA5IDE4OjA1OjQ3Ii8+CiAgICA8Z3JhbW1hcnM+CiAgICAgICAgPGluY2x1ZGUgaHJlZj0iaHR0cDovL2xvY2FsaG9zdDo4MDgwL29kYWxpYy9hcHBsaWNhdGlvbi53YWRsL3hzZDAueHNkIj4KICAgICAgICAgICAgPGRvYyB0aXRsZT0iR2VuZXJhdGVkIiB4bWw6bGFuZz0iZW4iLz4KICAgICAgICA8L2luY2x1ZGU+CiAgICA8L2dyYW1tYXJzPgogICAgPHJlc291cmNlcyBiYXNlPSJodHRwOi8vbG9jYWxob3N0OjgwODAvb2RhbGljLyI+CiAgICAgICAgPHJlc291cmNlIHBhdGg9InRhc2tzL0xULTIwMDkvZXhlY3V0aW9uIj4KICAgICAgICAgICAgPG1ldGhvZCBpZD0icHV0RXhlY3V0aW9uRm9yVGFza0lkIiBuYW1lPSJQVVQiPgogICAgICAgICAgICAgICAgPHJlcXVlc3Q+CiAgICAgICAgICAgICAgICAgICAgPG5zMjpyZXByZXNlbnRhdGlvbiB4bWxuczpuczI9Imh0dHA6Ly93YWRsLmRldi5qYXZhLm5ldC8yMDA5LzAyIiB4bWxucz0iIiBlbGVtZW50PSJleGVjdXRpb24iIG1lZGlhVHlwZT0iYXBwbGljYXRpb24vanNvbiIvPgogICAgICAgICAgICAgICAgPC9yZXF1ZXN0PgogICAgICAgICAgICAgICAgPHJlc3BvbnNlPgogICAgICAgICAgICAgICAgICAgIDxyZXByZXNlbnRhdGlvbiBtZWRpYVR5cGU9ImFwcGxpY2F0aW9uL2pzb24iLz4KICAgICAgICAgICAgICAgIDwvcmVzcG9uc2U+CiAgICAgICAgICAgIDwvbWV0aG9kPgogICAgICAgICAgICA8bWV0aG9kIGlkPSJkZWxldGVFeGVjdXRpb25Gb3JUYXNrSWQiIG5hbWU9IkRFTEVURSI+CiAgICAgICAgICAgICAgICA8cmVzcG9uc2U+CiAgICAgICAgICAgICAgICAgICAgPHJlcHJlc2VudGF0aW9uIG1lZGlhVHlwZT0iYXBwbGljYXRpb24vanNvbiIvPgogICAgICAgICAgICAgICAgPC9yZXNwb25zZT4KICAgICAgICAgICAgPC9tZXRob2Q+CiAgICAgICAgPC9yZXNvdXJjZT4KICAgIDwvcmVzb3VyY2VzPgo8L2FwcGxpY2F0aW9uPgo=" 
.15:34:15.035 [http-nio-8080-exec-5] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting PUT for path tasks/LT-2009/execution 
.15:34:15.039 [http-nio-8080-exec-5] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Reply {
  "status" : 200,
  "type" : "MESSAGE",
  "payload" : {
    "text" : "Execution submitted.",
    "additionalResources" : [ ],
    "debugContent" : null
  }
} 
.15:34:15.047 [http-nio-8080-exec-3] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting GET for path tasks/LT-2009/state 
.15:34:15.048 [http-nio-8080-exec-3] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Reply {
  "status" : 200,
  "type" : "DATA",
  "payload" : "ERROR"
} 
.15:34:18.117 [http-nio-8080-exec-6] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Requesting GET for path tasks/LT-2009/state 
.15:34:18.117 [http-nio-8080-exec-6] DEBUG c.c.m.x.o.a.r.f.LoggingResponseFilter - Reply {
  "status" : 200,
  "type" : "DATA",
  "payload" : "ERROR"
} 
```

<img width="967" alt="screen shot 2016-11-30 at 15 32 12" src="https://cloud.githubusercontent.com/assets/3014917/20756263/561aab82-b712-11e6-8c9d-947ad1b21f3c.png">

There is really a need to have better information about which error occurred!

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: http://data.vorarlberg.gv.at/katalog/politik/LT-2009.csv
- Note: The original file is not correctly formatted. First line (header) is not ended by semicolon, but other lines are ended by semicolon, so they have one more column (which is empty). So that the task execution ended by error. The UI displayed the error statement, but user cannot recognize, that the error was caused by bad formatting of the input file:
![lt-2009_error](https://cloud.githubusercontent.com/assets/17772934/21080343/aa758ea2-bfac-11e6-9998-be81dfaeca4f.png)

Then I added a semicolon to the first line.
File: http://data.vorarlberg.gv.at/katalog/politik/LT-2009.csv with added semicolon on the first line (reduced to 20 lines)

Result - against Jan's (reduced) DBpedia, original DBpedia and German DBpedia):
![lt-2009_result](https://cloud.githubusercontent.com/assets/17772934/21080358/136b2b4c-bfad-11e6-8f54-0905baf3616f.png)

![lt-2009_relations](https://cloud.githubusercontent.com/assets/17772934/21080360/20394f2a-bfad-11e6-90f9-762c102c4a01.png)

Classification:
- Gemeinde and Bezirk all, but differently
- other columns not (expected, just numeric values) (ÖVP just German DBpedia, but wrongly)

Disambiguation:
- Gemeinde and Bezirk just very few lines and differently
- other columns are just numeric values

Subject column:
- Gemeinde always - seems OK

Relations:
- Gemeinde -> Bezirk (bezirk / district) seems OK (except German DBpedia)
- Gemeinde -> ÖVP (areaCode) only in German DBpedia, but not correct

Other:
- Special German characters, e.g. Ö, not correctly displayed
- UI - result - first step: not all rows are displayed (just 10 rows are displayed), not proper highlighting of even and odd rows)
- no problem when input contains completely empty last column

Complete data (original and corrected reduced file, screens, exports and caches) attached:
[LT-2009.zip](https://github.com/odalic/sti/files/644470/LT-2009.zip)

**Comment by tomas-knap** [comment]
Covered by https://github.com/odalic/sti/issues/288
