### ISSUE TITLE
ODP: Top 1001 IT-Unternehmen Österreichs

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#178]
https://grips.semantic-web.at/x/sASBB

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: http://data.opendataportal.at/dataset/3ceab8ea-7bc8-4270-b62a-f7538569d1b1/resource/ec8d299d-c555-4bc8-aed0-55eb694dd094/download/export191015.csv

Task execution ended by error. The UI displayed the error statement, but user cannot recognize what is the reason of the error:
![companies_error](https://cloud.githubusercontent.com/assets/17772934/21081620/25d75a94-bfcb-11e6-926b-2300768fa5de.png)
The original file is not correctly formatted. Not all rows have the same count of columns. There are more rows with less columns than other. The error is not thrown during input file processing. It is thrown during algorithm run, when it wants to get content of some cell of the input table and the null value is returned, so that the NullPointerException is thrown.

**Comment by tomas-knap** [comment]
Covered by https://github.com/odalic/sti/issues/288
