### ISSUE TITLE
Abstammung 2015 (enumeration of people)

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#183]
https://grips.semantic-web.at/x/sASBB

**Comment by josef-janousek** [comment]
Version: develop 11.12.2016
File: http://data.linz.gv.at/katalog/population/abstammung/2015/auslg_2015.csv

Task execution ended by error. The UI displayed the error statement, but user cannot recognize what is the reason of the error:
![auslg_2015_error](https://cloud.githubusercontent.com/assets/17772934/21083687/4b2878b6-bff6-11e6-98a6-28b9690d9086.png)
In the original file text fields (in the first row) are wrapped in quotes). Currently the program is not prepared for this file configuration. The error was not thrown during input file processing. Then the error was caused by SPARQLProxy and the method queryEntityCandidates when the query string contained quotes, These strings are problematic for this query method.

Then I removed all quotes.
File: http://data.linz.gv.at/katalog/population/abstammung/2015/auslg_2015.csv with removed quotes (all 85 lines)

Result - against Jan's (reduced) DBpedia, original DBpedia and German DBpedia:
![auslg_2015_result](https://cloud.githubusercontent.com/assets/17772934/21083502/39cd27a0-bff2-11e6-9428-a13f1705f9df.png)

![auslg_2015_relations](https://cloud.githubusercontent.com/assets/17772934/21083503/41de79a8-bff2-11e6-8b9c-1a324362552c.png)

Classification:
- Nationalität all, but partially good (Place)
- other columns not (expected, just numeric values) (Männer just DBpedia, but wrongly)

Disambiguation:
- Nationalität sometimes all OK, sometimes just DBpedia, sometimes two of KBs, sometimes nothing
- other columns are just numeric values

Subject column:
- Nationalität always - OK

Relations:
- No relations were expected, DBpedia found one, but wrong (point)

Other:
- Special German characters, e.g. ä, not correctly displayed
- UI - result - first step: not all rows are displayed (just 47 from 85 rows are displayed), this leads to not proper highlighting of even and odd rows (due to missing rows)

Complete data (original and reduced file, screens, exports and caches) attached:
[auslg_2015.zip](https://github.com/odalic/sti/files/644833/auslg_2015.zip)

**Comment by tomas-knap** [comment]
Covered by https://github.com/odalic/sti/issues/288
