### ISSUE TITLE
Implement prevent disambiguation feedback

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#209]
_From @brodecva on November 17, 2016 13:50_

Should be trivial now, when we support empty chosen set.

_Copied from original issue: odalic/odalic-ui#141_

**Comment by tomas-knap** [comment]
This could be realized by removing the disamb. entities from the cell, right? Because as the disamb. entities are removed, the cell is also locked. So is there any further need to work on that issue? Because I think it works now (as is described above), which is enough. 

And the use case "prevent all cell values in the given column to be disambiguated" can be realized by "remove all disambiguations" - which should be done in 5th iter

**Comment by brodecva** [comment]
> This could be realized by removing the disamb. entities from the cell, right? Because as the disamb. entities are removed, the cell is also locked. So is there any further need to work on that issue? Because I think it works now (as is described above), which is enough.

And the use case "prevent all cell values in the given column to be disambiguated" can be realized by "remove all disambiguations" - which should be done in 5th iter

Yeah, this is exactly how we do it.
