### ISSUE TITLE
Add read only API supporting listing of available KBs

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#224]
In order to prevent the UI from relying on a hard-wired list.

**Comment by tomas-knap** [comment]
@brodecva This was also closed, does that mean that it was already implemented? Or what is the status?

**Comment by brodecva** [comment]
@tomas-knap Oh, I did it again. Forgot to link the issues, it was accepted as pull request https://github.com/odalic/sti/pull/246.

**Comment by tomas-knap** [comment]
Ok, thanks, it is great that we have this! 

Would like to provide Odalic release by the end of December and also send out to more users, so that they can do some usability tests, so we need to solve these rather minor issues, such as hardcoded KBs, support for commas, which may be quite confusing for the users.
