### ISSUE TITLE
Implement property (aka relation) proposal

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#263]
Hi, I have entirely overlooked this, but this feature is still not implemented (the API is ready) for the properties.

**Comment by brodecva** [comment]
@JanVana Hi, any progress?

**Comment by JanVana** [comment]
I have started implementing this feature, but I am a bit confused by the design. The method is creating a new property, but where is a method for assigning a property to some resource? (creating a subject property object triple)

**Comment by tomas-knap** [comment]
@brodecva Can answer probably better, but in general, properties are first-class citizens - so you can propose new Predicate/Property, which works in the same way as when proposing Class (but it is an instance of Property (ObjectProperty/DataProperty), not of Class). Otherwise it works in a similar way as when proposing Classes for columns. Optionally, you may define domain/ranges for the properties. You do not generate any subject predicate object triples with particular instances.  E.g. for a sample predicate you may generate:

pc:contractPrice a owl:ObjectProperty ;
  rdfs:label "Cena"@cs, "Price"@en ;
  rdfs:comment "Abstraktní vlastnost pro cenu přiřazené k veřejné zakázce"@cs ;
  rdfs:comment "Abstract property for price of public contract"@en ;
  rdfs:domain pc:Contract ;
  rdfs:range gr:PriceSpecification .

**Comment by tomas-knap** [comment]
We will for sure come to that point tomorrow to clarify that.

**Comment by JanVana** [comment]
@tomas-knap Thank you for explaining this to me.

This issue is implemented in the 263 branch and can be merged.

**Comment by brodecva** [comment]
@JanVana Thanks! Merged. Now it is up to @KataBoku to provide the UI part.
