### ISSUE TITLE
Cannot find proposed resource by its label

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#338]

**Comment by brodecva** [comment]
@JanVana Well it does not seem to work most of the time. Some resources eventually appeared after cache removal. Cannot recognize the pattern though.

**Comment by brodecva** [comment]
@JanVana Hi, this is rather important. It also blocks your latest pull request. Could you please look at this first?

**Comment by JanVana** [comment]
@brodecva  I have tested several inserts today a it seems the issue can be caused by two reasons:

1)  The classification of the column is not, what we consider a class. This is connected to the issue #312 a limitations of the search dialog. Can't be fixed unless we address #312 and it seems to me we won't be addressing it in the project.

2) The fulltext catalog takes some time to add to catalogue new triples. If you just wait a minute, the proposed result will appear.

**Comment by JanVana** [comment]
We agreed on removing class restrictions on resource search.

**Comment by tomas-knap** [comment]
Test, otherwise ready

**Comment by JanVana** [comment]
Implemented in pull request #354
