### ISSUE TITLE
Integration with CSVClean

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#360]
Testing CSVClean integration - just test, write down results
- Can be used to pre-clean the CSV before being processed

**Comment by tomas-knap** [comment]
The service is available at: http://data.wu.ac.at/csvengine/csv/clean

I will provide you also with the github repo - contacting authors...

**Comment by tomas-knap** [comment]
The idea is just to try that out (try to load something to csvcleaner) to see whether it makes sense (in the future) to integrate csvclean as a service for cleansing CSV files before Odalic core runs.

**Comment by tomas-knap** [comment]
This is low prio (in terms of the software project)

**Comment by josef-janousek** [comment]
First try:
- file: http://data.vorarlberg.gv.at/katalog/politik/LT-2009.csv
- cleaning needed: First line (header) is not ended by semicolon, but other lines are ended by semicolon, so they have one more column (which is empty).
Result of CSVClean:
![unicodeerror](https://cloud.githubusercontent.com/assets/17772934/22756069/338c260c-ee46-11e6-80e3-6139e6c86dd7.png)
(because the file is not UTF-8 encoded)
Result after change encoding to UTF8:
![indexerror](https://cloud.githubusercontent.com/assets/17772934/22756136/7a55f5ea-ee46-11e6-9af0-1fe733b8b881.png)

**Comment by tomas-knap** [comment]
Yes, I think that is enough for now :-)
