### ISSUE TITLE
Feedback not properly saved for classification, disambiguation, relation discovery

### ISSUE THREAD

**Issue by tomas-knap** [odalic/sti#458]
Steps to reproduce: 
1) Run Book-v1 task against dbpedia Jan
2) remove the class for first column, click Save feedback. 
3) return to the list of tasks
4) Reopen the same task - the classification is again there although it was removed in step 2

The same if you remove disambiguation or relation, or change classification, disambiguation, relation. It works only for subject columns!

**Comment by brodecva** [comment]
Well, this does not sound good at all.

**Comment by brodecva** [comment]
We have thoroughly discussed this and t proved to be a major flaw in the server-client interaction design, where the client is currently unable to apply the feedback when re-entering the screen, because it is too tightly coupled with the UI result model which is lost when the user leaves the screen.
In the end we went with @josef-janousek idea to solution, which I am implementing and that is to merge the feedback provided by the client. If that fails some workaround might ne introdcued...

**Comment by brodecva** [comment]
Fixed in https://github.com/odalic/sti/pull/460 .

**Comment by tomas-knap** [comment]
@brodecva Can you pls describe a bit more the issue and the selected solution?
