### ISSUE TITLE
Convert the Result to annotation table model

### ISSUE THREAD

**Issue by brodecva** [odalic/sti#99]
Add conversion class.

**Comment by brodecva** [comment]
Hi, after some discussion concerning the delay, we found that @josef-janousek  needs to clarify some things in order to successfully finish the task. Could you please, @tomas-knap , help him answer the following querstion concerning the model of standard annotated table ( https://grips.semantic-web.at/x/6QxbB )?
- titles array field - where to get them? I am under the impression that they are the labels of classifications from non-primary KB, am I right?
- dc:description field - is it possible to get it from the TM result? And what is its relation to titles, concept labels? I almost suspect that it is something that the KB has to be additionally queried for...
- separator field - meaning? usage?

Thank you very much! @josef-janousek will probably contact you tomorrow anyway. If you'll need me, I'll be also available.

Also, @josef-janousek , consider if some of these problems cannot be resolved by consulting the associated specs in the document.

**Comment by tomas-knap** [comment]
Basically titles array should contain titles of all classes classifying the given column (selected by the algorithm/adjusted by the user) + also the column header name itself.  

Regarding descriptions, please do not consider them for now. 

The separator field defines the separator character used to separate more values within single cell value. For example, in case of alternative disambiguations, there can be more values, so separator is defined, so that the algorithm generating RDF data later knows how to parse such array of values within one cell. 

@josef-janousek Lets have a short call tomorrow morning

**Comment by tomas-knap** [comment]
As part of conversion, it is also necessary to create "extended" CSV file, which contains the original CSV file enriched with columns containing disambiguation, alternative disambiguations!

**Comment by brodecva** [comment]
>As part of conversion, it is also necessary to create "extended" CSV file, which contains the original CSV file enriched with columns containing disambiguation, alternative disambiguations!

Yes, we talked about splitting this original issue into two and forgot to create the second one. It is here: https://github.com/odalic/sti/issues/110

> Also what is missing is the creation of the JSON file itself.

Already covered by a separate issue (created as a reaction to delay in the original issue, in order to somewhat manage the consequences of it): https://github.com/odalic/sti/issues/82 . @josef-janousek has been thoroughly instructed by me about the means of JSON mapping and publication in our API.
